apiVersion: v1
kind: Service
metadata:
  name: taski-deployment
  labels:
    project: bvhw
spec:
  type: LoadBalancer
  selector:
    project: bvhw
  ports:
  - name: front
    port: 3000
    targetPort: 3000
  - name: back
    port: 8000
    targetPort: 8000
  - name: forw
    port: 80
    targetPort: 80

  
