apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app  : my-app
    env  : dev
    owner: AlexanderGorshkov
spec:
  replicas: 2
  selector:
    matchLabels:
      project: bvhw
  template:
    metadata:
      labels:
        project: bvhw
    spec:
      containers:
        - name: front
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-data-volume
              mountPath: /var/www/html
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/
        - name: radish
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: radish-data-volume
              mountPath: /data
        - name: tomcat
          image: tomcat:8.5.38
          ports:
            - containerPort: 8080
      volumes:
            - name: nginx-data-volume
              hostPath:
                path: html-templ
                type: DirectoryOrCreate
            - name: nginx-config-volume
              hostPath:
                path: nginx
                type: DirectoryOrCreate
            - name: radish-data-volume
              hostPath:
                path: redisdata
                type: DirectoryOrCreate

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    env: dev
    owner: AlexanderGorshkov
spec:
  selector:
    project: bvhw
  ports:
    - name: nginx-listener
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30030
    - name: radish-listener
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30031
    - name: tomcat-listener
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30032
  type: NodePort
