name: "CI/CD deploy"
on:
  push:
    branches:
      - main
    paths: 
      - 'final-boss/taski/frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Yandex.Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.AUTHORIZED_KEY }}
      
      - name: Build and push Docker image to Yandex.Cloud Container Registry
        env:
          CR_REGISTRY: crp2s7naad8mvn5t5u8j
          CR_REPOSITORY: exchange
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/frontend:$IMAGE_TAG ./final-boss/taski/frontend/
          docker push cr.yandex/$CR_REGISTRY/frontend:$IMAGE_TAG
          docker build -t cr.yandex/$CR_REGISTRY/backend:$IMAGE_TAG ./final-boss/taski/backend/
          docker push cr.yandex/$CR_REGISTRY/backend:$IMAGE_TAG
          docker build -t cr.yandex/$CR_REGISTRY/nginx:$IMAGE_TAG ./final-boss/taski/nginx/
          docker push cr.yandex/$CR_REGISTRY/nginx:$IMAGE_TAG

      - name: Deploy to VPC-Server
        uses: actions/checkout@v3
        with:
          host: 158.160.159.107
          username: buka
          key: ${{ secrets.VPC_SSH_KEY }}
          port: 22
        env:
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          run: |
            echo $OAUTH_TOKEN|docker login --username oauth --password-stdin cr.yandex
            docker pull cr.yandex/crp2s7naad8mvn5t5u8j/frontend:${{ github.sha }}
            docker pull cr.yandex/crp2s7naad8mvn5t5u8j/backend:${{ github.sha }}
            docker pull cr.yandex/crp2s7naad8mvn5t5u8j/nginx:${{ github.sha }}
            docker run -p 3000:3000 -d cr.yandex/crp2s7naad8mvn5t5u8j/frontend:${{ github.sha }}
            docker run -p 8000:8000 -d cr.yandex/crp2s7naad8mvn5t5u8j/backend:${{ github.sha }}
            docker run -p 80:80 -d cr.yandex/crp2s7naad8mvn5t5u8j/nginx:${{ github.sha }}

