name: "CI/CD deploy"
on:
  push:
    branches:
      - main
    paths: 
      - 'final-boss/taski/frontend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Yandex.Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.AUTHORIZED_KEY }}
      
      - name: Build and push Docker image to Yandex.Cloud Container Registry
        env:
          CR_REGISTRY: crpcmdivflbbl644gkoh
          CR_REPOSITORY: exchange
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$IMAGE_TAG/frontend:$IMAGE_TAG ./final-boss/taski/frontend/
          docker push cr.yandex/$CR_REGISTRY/$IMAGE_TAG/frontend:$IMAGE_TAG
      #     docker build -t cr.yandex/$CR_REGISTRY/$IMAGE_TAG/backend:$IMAGE_TAG ./final-boss/taski/backend/
      #     docker push cr.yandex/$CR_REGISTRY/$IMAGE_TAG/backend:$IMAGE_TAG
      #     docker docker build -t cr.yandex/$CR_REGISTRY/$IMAGE_TAG/nginx:$IMAGE_TAG ./final-boss/taski/nginx/
      #     docker push cr.yandex/$CR_REGISTRY/$IMAGE_TAG/nginx:$IMAGE_TAG

      - name: Deploy to VPC-Server
        uses: appleboy/ssh-action@master
        with:
          host: 158.160.140.27
          username: buka
          key: ${{ secrets.VPC_SSH_KEY }}
          port: 22
      
      - name: Run command on VPC-Server
        env:
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          run: |
            sudo docker login --username oauth --password $OAUTH_TOKEN cr.yandex
            if ["$(docker ps -q)]; then 
              sudo docker kill $(docker ps -q) &> /dev/null
            fi
            if ["$(docker ps -a -q)"]; then
              sudo docker rm $(docker ps -a -q) &> /dev/null
            fi
            sudo docker run -dp 80:3000 cr.yandex/$CR_REGISTRY/$IMAGE_TAG/frontend:$IMAGE_TAG
